# -*- coding: utf-8 -*-
"""Manifiesto de cursos: fuente de verdad de la sidebar y de la cadena prev/next.

Lo consume scripts/sync-nav.py. El orden de `pages` define el orden de la sidebar;
`nav_order` (opcional) define un orden distinto para la cadena prev/next.
Sembrado desde el repo el 2026-09-02; desde aquí en adelante es la fuente de verdad.
"""

COURSES = {
    'electro': {
        'icon': '⚡',
        'name': 'Electromagnetismo',
        'subtitle': 'Auxiliares 1 – 25',
        'blocks': [
            'Campo eléctrico',
            'Potencial y conductores',
            'Dipolos',
            'Dieléctricos',
            'Corrientes',
            'Magnetismo',
            'Inducción',
            'Materia magnética',
        ],
        # slug, num, etiqueta sidebar, unidad, bloque, título para el prev/next
        'pages': [
            ('aux_1' , '01', 'Campo Eléctrico'          , 'u1', 'Campo eléctrico'        , 'Campo Eléctrico'),
            ('aux_2' , '02', 'Ley de Gauss'             , 'u1', 'Campo eléctrico'        , 'Ley de Gauss'),
            ('aux_3' , '03', 'Gauss — Parte 2'          , 'u1', 'Campo eléctrico'        , 'Ley de Gauss — Parte 2'),
            ('aux_4' , '04', 'Potencial Eléctrico'      , 'u2', 'Potencial y conductores', 'Potencial Eléctrico'),
            ('aux_5' , '05', 'Potencial y Conductores'  , 'u2', 'Potencial y conductores', 'Potencial y Conductores'),
            ('aux_6' , '06', 'Conductores'              , 'u2', 'Potencial y conductores', 'Conductores'),
            ('aux_7' , '07', 'Conductores y Laplace'    , 'u2', 'Potencial y conductores', 'Conductores y Laplace'),
            ('aux_8' , '08', 'Conductores II'           , 'u2', 'Potencial y conductores', 'Conductores II'),
            ('aux_9' , '09', 'Carga Imagen'             , 'u2', 'Potencial y conductores', 'Método de Carga Imagen'),
            ('aux_10', '10', 'Pre-control'              , 'u3', 'Dipolos'                , 'Pre-control'),
            ('aux_11', '11', 'Dipolos'                  , 'u3', 'Dipolos'                , 'Dipolos'),
            ('aux_12', '12', 'Condensadores'            , 'u4', 'Dieléctricos'           , 'Condensadores con Dieléctricos'),
            ('aux_13', '13', 'Dieléctricos'             , 'u4', 'Dieléctricos'           , 'Dieléctricos'),
            ('aux_14', '14', 'Dieléctricos II'          , 'u4', 'Dieléctricos'           , 'Dieléctricos II'),
            ('aux_15', '15', 'Corrientes y Resistencias', 'u5', 'Corrientes'             , 'Corrientes y Resistencias'),
            ('aux_16', '16', 'Circuitos'                , 'u5', 'Corrientes'             , 'Circuitos'),
            ('aux_17', '17', 'Fuerza de Lorentz'        , 'u6', 'Magnetismo'             , 'Fuerza de Lorentz'),
            ('aux_18', '18', 'Ley de Ampère'            , 'u6', 'Magnetismo'             , 'Ley de Ampère'),
            ('aux_19', '19', 'Ampère — Parte 2'         , 'u6', 'Magnetismo'             , 'Ampère — Parte 2'),
            ('aux_20', '20', 'Fuerzas sobre carga'      , 'u6', 'Magnetismo'             , 'Fuerzas sobre carga puntual'),
            ('aux_21', '21', 'Faraday-Lenz'             , 'u6', 'Inducción'              , 'Faraday-Lenz'),
            ('aux_22', '22', 'Faraday-Lenz II'          , 'u6', 'Inducción'              , 'Faraday-Lenz II'),
            ('aux_23', '23', 'Vector Magnetización'     , 'u6', 'Materia magnética'      , 'Vector de Magnetización'),
            ('aux_24', '24', 'Magnetización pt. 2'      , 'u6', 'Materia magnética'      , 'Magnetización — Parte 2'),
            ('aux_25', '25', 'Vector H'                 , 'u6', 'Materia magnética'      , 'Vector Intensidad Magnética'),
        ],
    },
    'termo': {
        'icon': '⚛️',
        'name': 'Termodinámica',
        'subtitle': 'Cátedras 1–28 · CC 1–11',
        'blocks': [
            'Introducción',
            'Gas ideal y cinética',
            'Primera Ley',
            'Segunda Ley',
            'Estadística y fases',
            'Estadística avanzada',
            'Clases complementarias',
            'Ciclos y Máquinas',
            'Gases Reales y Transporte',
        ],
        # slug, num, etiqueta sidebar, unidad, bloque, título para el prev/next
        'pages': [
            ('cat_1' , '01'  , 'Introducción'         , 'u1', 'Introducción'             , 'Introducción a la Termodinámica'),
            ('cat_2' , '02'  , 'Historia del Calor'   , 'u1', 'Introducción'             , 'Historia: Calor y Máquinas'),
            ('cat_3' , '03'  , 'Teoría Cinética'      , 'u2', 'Gas ideal y cinética'     , 'Teoría Cinética y Presión'),
            ('cat_4' , '04'  , 'Temperatura'          , 'u2', 'Gas ideal y cinética'     , 'Temperatura y Equilibrio Térmico'),
            ('cat_5' , '05'  , 'Dist. de Maxwell'     , 'u2', 'Gas ideal y cinética'     , 'Distribución de Maxwell'),
            ('cat_6' , '06'  , 'Primera Ley'          , 'u3', 'Primera Ley'              , 'Primera Ley de la Termodinámica'),
            ('cat_7' , '07'  , 'Procesos'             , 'u3', 'Primera Ley'              , 'Procesos Termodinámicos'),
            ('cat_8' , '08'  , 'Cap. Calórica'        , 'u3', 'Primera Ley'              , 'Capacidad Calórica'),
            ('cat_9' , '09'  , 'Clausius y Kelvin'    , 'u4', 'Segunda Ley'              , 'Segunda Ley: Clausius y Kelvin'),
            ('cat_10', '10'  , 'Entropía y Carnot'    , 'u4', 'Segunda Ley'              , 'Entropía y Ciclo de Carnot'),
            ('cat_11', '11'  , 'Mec. Estadística'     , 'u5', 'Estadística y fases'      , 'Mecánica Estadística'),
            ('cat_12', '12'  , 'Transic. de Fase'     , 'u5', 'Estadística y fases'      , 'Transiciones de Fase'),
            ('cat_13', '13'  , 'Func. de Partición'   , 'u5', 'Estadística avanzada'     , 'Función de Partición'),
            ('cat_14', '14'  , 'Ensemble Canónico'    , 'u5', 'Estadística avanzada'     , 'Ensemble Canónico'),
            ('cat_15', '15'  , 'Potenciales Termod.'  , 'u5', 'Estadística avanzada'     , 'Potenciales Termodinámicos'),
            ('cat_16', '16'  , 'Multicomponentes'     , 'u5', 'Estadística avanzada'     , 'Sistemas Multicomponentes'),
            ('cat_17', '17'  , 'Fluctuaciones'        , 'u5', 'Estadística avanzada'     , 'Fluctuaciones'),
            ('cat_18', '18'  , 'Transform. Legendre'  , 'u5', 'Estadística avanzada'     , 'Transformadas de Legendre'),
            ('cat_19', '19'  , 'Gran Ensemble'        , 'u5', 'Estadística avanzada'     , 'Gran Ensemble Canónico'),
            ('cat_20', '20'  , 'Síntesis'             , 'u5', 'Estadística avanzada'     , 'Síntesis del Curso'),
            ('cc_1'  , 'CC1' , 'Conceptos Fund.'      , 'u3', 'Clases complementarias'   , 'CC1: Conceptos Fundamentales'),
            ('cc_2'  , 'CC2' , 'Temperatura'          , 'u3', 'Clases complementarias'   , 'CC2: Temperatura'),
            ('cc_3'  , 'CC3' , 'Procesos Básicos'     , 'u3', 'Clases complementarias'   , 'CC3: Procesos Básicos'),
            ('cc_4'  , 'CC4' , 'Proc. Adiabáticos'    , 'u3', 'Clases complementarias'   , 'CC4: Procesos Adiabáticos'),
            ('cc_5'  , 'CC5' , 'Modelo Atómico'       , 'u3', 'Clases complementarias'   , 'CC5: Modelo Atómico'),
            ('cc_6'  , 'CC6' , 'Entropía'             , 'u3', 'Clases complementarias'   , 'CC6: Entropía y Segunda Ley'),
            ('cc_7'  , 'CC7' , 'Métodos Matemát.'     , 'u3', 'Clases complementarias'   , 'CC7: Métodos Matemáticos'),
            ('cat_21', '21'  , 'Entropía Irreversible', 'u6', 'Ciclos y Máquinas'        , 'Entropía Irreversible'),
            ('cat_22', '22'  , 'Máquinas Térmicas'    , 'u6', 'Ciclos y Máquinas'        , 'Máquinas Térmicas'),
            ('cat_23', '23'  , 'Ciclo de Carnot'      , 'u6', 'Ciclos y Máquinas'        , 'Ciclo de Carnot'),
            ('cc_8'  , 'CC8' , 'Máq. de Carnot'       , 'u6', 'Ciclos y Máquinas'        , 'CC8: Máquinas de Carnot'),
            ('cc_9'  , 'CC9' , 'Entropía (Clausius)'  , 'u6', 'Ciclos y Máquinas'        , 'CC9: Entropía (Clausius)'),
            ('cat_24', '24'  , 'Equipartición y Pauli', 'u7', 'Gases Reales y Transporte', 'Equipartición y Pauli'),
            ('cat_25', '25'  , 'Hacia Gases Reales'   , 'u7', 'Gases Reales y Transporte', 'Hacia Gases Reales'),
            ('cat_26', '26'  , 'Van der Waals'        , 'u7', 'Gases Reales y Transporte', 'Van der Waals'),
            ('cat_27', '27'  , 'Coexistencia de Fases', 'u7', 'Gases Reales y Transporte', 'Coexistencia de Fases'),
            ('cat_28', '28'  , 'Síntesis y Browniano' , 'u7', 'Gases Reales y Transporte', 'Síntesis y Browniano'),
            ('cc_10' , 'CC10', 'Teorema del Virial'   , 'u7', 'Gases Reales y Transporte', 'CC10: Teorema del Virial'),
            ('cc_11' , 'CC11', 'Licuefacción'         , 'u7', 'Gases Reales y Transporte', 'CC11: Licuefacción'),
        ],
        # La cadena prev/next NO sigue el orden de la sidebar (ver docs/sidebar-maintenance.md §6).
        # Borrar este campo para que prev/next siga el hilo temático de la sidebar.
        'nav_order': [
            'cat_1', 'cat_2', 'cat_3', 'cat_4', 'cat_5', 'cat_6',
            'cat_7', 'cat_8', 'cat_9', 'cat_10', 'cat_11', 'cat_12',
            'cat_13', 'cat_14', 'cat_15', 'cat_16', 'cat_17', 'cat_18',
            'cat_19', 'cat_20', 'cat_21', 'cat_22', 'cat_23', 'cat_24',
            'cat_25', 'cat_26', 'cat_27', 'cat_28', 'cc_1', 'cc_2',
            'cc_3', 'cc_4', 'cc_5', 'cc_6', 'cc_7', 'cc_8',
            'cc_9', 'cc_10', 'cc_11',
        ],
    },
    'termoquimica': {
        'icon': '🧪',
        'name': 'Termodinámica Química',
        'subtitle': 'IQ2212 · Clases 1–8 · Aux 1–4',
        'blocks': [
            'Gases ideales',
            'Gases reales',
            'Primera ley',
            'Termoquímica',
        ],
        # slug, num, etiqueta sidebar, unidad, bloque, título para el prev/next
        'pages': [
            ('clase_1', '01', 'Gas Ideal y Dalton'   , 'u1', 'Gases ideales', 'Gas Ideal, Leyes Empíricas y Ley de Dalton'),
            ('aux_1'  , 'A1', 'Gases Ideales'        , 'u1', 'Gases ideales', 'Gases Ideales'),
            ('clase_2', '02', 'Van der Waals'        , 'u2', 'Gases reales' , 'Desviaciones del Gas Ideal y Ecuación de Van der Waals'),
            ('clase_3', '03', 'Estados Correspond.'  , 'u2', 'Gases reales' , 'Punto Crítico y Ley de los Estados Correspondientes'),
            ('aux_2'  , 'A2', 'Gases Reales'         , 'u2', 'Gases reales' , 'Gases Reales'),
            ('clase_4', '04', 'Ley Cero, Q y W'      , 'u3', 'Primera ley'  , 'Ley Cero, Trabajo y Calor'),
            ('clase_5', '05', 'Energía y Entalpía'   , 'u3', 'Primera ley'  , 'Energía Interna, Capacidades Caloríficas y Entalpía'),
            ('clase_6', '06', 'Cp−Cv y Joule-Thomson', 'u3', 'Primera ley'  , 'Relación entre Cp y Cv, y Efecto Joule-Thomson'),
            ('aux_3'  , 'A3', 'Primera Ley'          , 'u3', 'Primera ley'  , 'Primera Ley'),
            ('aux_4'  , 'A4', 'Primera Ley II'       , 'u3', 'Primera ley'  , 'Primera Ley II'),
            ('clase_7', '07', 'Calor de Reacción'    , 'u4', 'Termoquímica' , 'Calor de Reacción y Entalpías de Formación'),
            ('clase_8', '08', 'Hess y Kirchhoff'     , 'u4', 'Termoquímica' , 'Ley de Hess y Ecuación de Kirchhoff'),
        ],
    },
}
